[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_swap_dapp = "CDvQtfPPKVkAfrcC9PJuQYFdj46Zk2fje2q4rmpgT6dh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
